export const Users = [
  {
    id: 1,
    profilePicture: "pic.jpg",
    username: "tomerb1",
  },
  {
    id: 2,
    profilePicture: "pic.jpg",
    username: "tomerb2",
  },
  {
    id: 3,
    profilePicture: "pic.jpg",
    username: "tomerb3",
  },
  {
    id: 4,
    profilePicture: "pic.jpg",
    username: "tomerb4",
  },
  {
    id: 5,
    profilePicture: "pic.jpg",
    username: "tomerb5",
  },
  {
    id: 6,
    profilePicture: "pic.jpg",
    username: "tomerb6",
  },
  {
    id: 7,
    profilePicture: "pic.jpg",
    username: "tomerb7",
  },
  {
    id: 8,
    profilePicture: "pic.jpg",
    username: "tomerb8",
  },
  {
    id: 9,
    profilePicture: "pic.jpg",
    username: "tomerb9",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "some description",
    photo: "pic.jpg",
    date: "5 min ago",
    userId: 1,
    like: 33,
    comment: 9,
  },
  {
    id: 2,
    desc: "some description",
    date: "2 min ago",
    userId: 2,
    like: 2,
    comment: 29,
    photo: "pic.jpg",
  },
  {
    id: 3,
    desc: "some description",
    date: "15 min ago",
    userId: 3,
    like: 21,
    comment: 5,
    photo: "pic.jpg",
  },
  {
    id: 4,
    desc: "some description",
    date: "55 min ago",
    userId: 4,
    like: 3,
    comment: 5,
    photo: "pic.jpg",
  },
  {
    id: 5,
    desc: "some description",
    date: "1 hour ago",
    userId: 5,
    like: 12,
    comment: 1,
    photo: "pic.jpg",
  },
  {
    id: 6,
    desc: "some description",
    date: "1 min ago",
    userId: 6,
    like: 353,
    comment: 91,
    photo: "pic.jpg",
  },
  {
    id: 7,
    desc: "some description",
    date: "5 hours ago",
    userId: 7,
    like: 3,
    comment: 9,
    photo: "pic.jpg",
  },
  {
    id: 8,
    desc: "some description",
    date: "15 min ago",
    userId: 8,
    like: 33,
    comment: 2,
    photo: "pic.jpg",
  },
  {
    id: 9,
    desc: "some description",
    date: "56 min ago",
    userId: 9,
    like: 3,
    comment: 0,
    photo: "pic.jpg",
  },
];
